<?php
$paymentInfo = $block->getOrderPaymentAmounts();

if ($paymentInfo['expected']) {

    $satoshi_expected = intval($paymentInfo['expected']);
    $satoshi_paid = intval($paymentInfo['paid']);

    $expected = $paymentInfo['expected']/1.0e8;
    
    if (is_numeric($paymentInfo['paid'])) {
        $paid = $paymentInfo['paid']/1.0e8 . ' BTC';
    } else {
        $paid = $paymentInfo['paid'];
    }
} else {
    $expected = 'Info not available';
    $paid = 'Info not available';
}

$txid = $block->getOrderTxId();
$addr = $block->getOrderAddr();

?>


<?php if ($addr) : ?>

<div class="top-margin"><b>Expected amount: </b><?php echo $expected?> BTC</div>
<div class="top-margin"><b>Paid amount: </b> <?php echo $paid?></div>
<div class="top-margin"><b>Bitcoin Transaction ID: </b> <a href="https://www.blockonomics.co/api/tx?txid=<?php echo $txid?>&addr=<?php echo $addr?>" target="_blank"><?php echo $txid?></a></div>
<div class="top-margin"><b>Order address: </b> <?php echo $addr?></div>


<?php endif ?>

<?php if ($txid && $satoshi_paid < $satoshi_expected) : ?>

<div class="top-margin error"><b>ERROR: </b> Paid BTC amount less than expected</div>

<?php endif ?>

<?php if ($txid && $satoshi_paid > $satoshi_expected) : ?>

<div class="top-margin"><b>Warning: </b> Paid BTC amount more than expected</div>

<?php endif ?>