<?php
/**
 * Blockonomics schema installation
 *
 * @category    Blockonomics
 * @package     Blockonomics_Merchant
 * @author      Blockonomics
 * @copyright   Blockonomics (https://blockonomics.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$btc_address = $block->getOrderBitcoinAddress();

if ($btc_address === '') {
    $btc_address = $block->getNewAddress();
    $orderTimestamp = $block->createNewBitcoinTransaction($btc_address);
} else {
    $orderTimestamp = $block->getOrderTimestamp();
}

$satoshi_amount = $block->getOrderPriceInBitcoin()/1.0e8;
$fiat_amount = $block->getOrderPriceInFiat();
$currency_code = $block->getCurrencyCode();
$altcoins_enables = $block->getAltcoinStatus();

$block->setSectretToSession();

$btc_href = "bitcoin:".$btc_address."?amount=".$satoshi_amount;

?>

<?php if ($btc_address != '') : ?>

<script type="text/x-magento-init">
{
    "#qrcode": {
        "Blockonomics_Merchant/js/createQr": {}
    }
}
</script>

<div id="btc-href" data-href="<?php echo $btc_href ?>"></div>
<div id="btc-address" data-address="<?php echo $btc_address ?>"></div>
<div id="btc-amount" data-address="<?php echo $satoshi_amount ?>"></div>
<div id="order-timestamp" data-timestamp="<?php echo $orderTimestamp ?>"></div>

<div id="paywrapper" class="payment-wrapper center">

    <?php if ($altcoins_enables) : ?>
    <div class="altcoin-select">
        <p>Pay with</p>
        <button id="btc" onclick="toggleCoin('btc')" type="button" class="active"><b>BTC</b></button><!--
    ---><button id="altcoin" onclick="toggleCoin('altcoin')" type="button"><b>Altcoins</b></button>
    </div>
    <?php endif ?>
    
    <div id="bnomics-btc-pane">
        <h3>Order# <?php echo $block->getOrderId(); ?></h3>
        <div class="clear"></div>
        <div class="info center">
            
            <p>To pay, please send exact amount of <span>BTC</span> to the <b>given address</b></p>
            <h2><?php echo $satoshi_amount ?> BTC</h2>
            <hr class="amount-seperator">
            <p>&asymp; <?php echo $fiat_amount?> <?php echo $currency_code?></p>
            <div class="address"><b><?php echo $btc_address ?></b></div>
        <div class="time-wrapper">
           <div id="time-left"></div>
            </div>
            <p><span id="time-left-minutes"></span> min left to pay your order</p>
            <p class="powered">Powered by Blockonomics</p>
        </div>
        <div class="qr-code-wrapper">
            <a id="btc-address-a" href="bitcoin:<?php echo $btc_address ?>?amount=<?php echo $satoshi_amount ?>">
                <div id="qrcode"></div>
            </a>
            <p>Click on the QR code open in the wallet</p>
        </div>
        <div class="clear"></div>
    </div>

    <?php if ($altcoins_enables) : ?>
    <div id="bnomics-altcoin-pane" class="bnomics-altcoin-pane">
        <h3>Order# <?php echo $block->getOrderId(); ?></h3>
        <div class="clear"></div>
        <h4>To pay, please click on the button below and choose your prefered Altcoin.</h4>
        <a onclick="pay_altcoins()" href="#"><img style="margin: auto;" src="https://shapeshift.io/images/shifty/small_dark_altcoins.png" class="ss-button"></a>
        <p class="powered">Powered by Blockonomics</p>
    </div>
    <?php endif ?>

</div>
<div id="altcoin-waiting" class="row">
    <div class="col-xs-12 altcoin-waiting">
        <h3>Waiting for BTC payment from shapeshift altcoin conversion</h3>
        <div class="bnomics-spinner"></div>
        <h3><a href="#" onclick="disableAltcoin()">Click here</a> to cancel and go back</h3>
    </div>
</div>
<div class="clear"></div>

<?php else : ?>

<div id="address-error">
    <h3>Could not generate new bitcoin address.</h3>
    <i>Note to webmaster: Your webhost is blocking outgoing HTTPS connections. Blockonomics requires an outgoing HTTPS (port 443) to generate new address. Check with your webhost to allow this. Also make sure that <a href="https://www.crybit.com/enable-allow_url_fopen/" target="_blank">allow_url_fopen is On</a> on your server. If issue persists, log a ticket on <a href="https://blockonomics.freshdesk.com/support/solutions/articles/33000215104-troubleshooting-unable-to-generate-new-address" target="_blank">http://blockonomics.freshdesk.com/</a></i>
</div>

<?php endif ?>